fix(decoding backtrace): change decoding_queue parameters and its using
sdcm.cluster.BaseNode.copy_scylla_debug_info function expects to get for 'node' object.
This object was received from decoding_queue.
But after the change presented in https://github.com/scylladb/scylla-cluster-tests/pull/4161
decoding_queue holds 'node_name' (string) instead of 'node' object. And it caused to failure of
decoding backtraces process with error:
failed to decode backtrace 'str' object has no attribute 'parent_cluster'

This commit presents fix for this problem: add 'node_ip' to the decoding_queue and then get node
object from node_ip.